name: 11_mini_project
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - abseil-cpp=20211102.0=he9d5cce_0
  - altair=5.0.1=py311hecd8cb5_0
  - appnope=0.1.2=py311hecd8cb5_1001
  - arrow-cpp=11.0.0=h89a8245_2
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=23.1.0=py311hecd8cb5_0
  - aws-c-common=0.6.8=h6c40b1e_1
  - aws-c-event-stream=0.1.6=hcec6c5f_6
  - aws-checksums=0.1.11=h6c40b1e_2
  - aws-sdk-cpp=1.8.185=h1a8d504_1
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.6.2=py311hecd8cb5_0
  - boost-cpp=1.82.0=ha357a0b_2
  - bottleneck=1.3.5=py311hb9e55a9_0
  - brotli=1.0.9=hca72f7f_7
  - brotli-bin=1.0.9=hca72f7f_7
  - brotlipy=0.7.0=py311h6c40b1e_1002
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.19.1=h6c40b1e_0
  - ca-certificates=2023.7.22=h8857fd0_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - category_encoders=2.6.1=py311hecd8cb5_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py311h6c40b1e_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py311hecd8cb5_0
  - comm=0.1.2=py311hecd8cb5_0
  - contourpy=1.0.5=py311ha357a0b_0
  - cryptography=41.0.3=py311h30e54ef_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - daal4py=2023.1.1=py311h85bffb1_0
  - dal=2023.1.1=ha357a0b_48680
  - debugpy=1.6.7=py311hcec6c5f_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hd8bbffd_0
  - gflags=2.2.2=h0a44026_0
  - giflib=5.2.1=h6c40b1e_3
  - gitdb=4.0.7=pyhd3eb1b0_0
  - gitpython=3.1.37=py311hecd8cb5_0
  - glog=0.5.0=h23ab428_0
  - grpc-cpp=1.48.2=h4ed1731_1
  - icu=73.1=hcec6c5f_0
  - idna=3.4=py311hecd8cb5_0
  - importlib-metadata=6.0.0=py311hecd8cb5_0
  - intel-openmp=2023.1.0=ha357a0b_43547
  - ipykernel=6.25.0=py311h85bffb1_0
  - ipython=8.15.0=py311hecd8cb5_0
  - ipywidgets=8.0.4=py311hecd8cb5_0
  - jedi=0.18.1=py311hecd8cb5_1
  - jinja2=3.1.2=py311hecd8cb5_0
  - joblib=1.2.0=py311hecd8cb5_0
  - jpeg=9e=h6c40b1e_1
  - jsonschema=4.17.3=py311hecd8cb5_0
  - jupyter_client=8.1.0=py311hecd8cb5_0
  - jupyter_core=5.3.0=py311hecd8cb5_0
  - jupyterlab_widgets=3.0.5=py311hecd8cb5_0
  - kiwisolver=1.4.4=py311hcec6c5f_0
  - krb5=1.20.1=h428f121_1
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libboost=1.82.0=hf53b9f2_2
  - libbrotlicommon=1.0.9=hca72f7f_7
  - libbrotlidec=1.0.9=hca72f7f_7
  - libbrotlienc=1.0.9=hca72f7f_7
  - libcurl=8.2.1=hf20ceda_0
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.17=hb664fd8_1
  - libedit=3.1.20221030=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libevent=2.1.12=h04015c4_1
  - libffi=3.4.4=hecd8cb5_0
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libiconv=1.16=hca72f7f_2
  - libnghttp2=1.52.0=h9beae6a_1
  - libpng=1.6.39=h6c40b1e_0
  - libprotobuf=3.20.3=hfff2838_0
  - libsodium=1.0.18=h1de35cc_0
  - libssh2=1.10.0=h04015c4_2
  - libthrift=0.15.0=h70b4b81_2
  - libtiff=4.5.1=hcec6c5f_0
  - libwebp=1.3.2=hf6ce154_0
  - libwebp-base=1.3.2=h6c40b1e_0
  - libxgboost=1.7.3=hcec6c5f_0
  - llvm-openmp=14.0.6=h0dcd299_0
  - lz4-c=1.9.4=hcec6c5f_0
  - markdown-it-py=2.2.0=py311hecd8cb5_1
  - markupsafe=2.1.1=py311h6c40b1e_0
  - matplotlib=3.7.2=py311hecd8cb5_0
  - matplotlib-base=3.7.2=py311h8251f7d_0
  - matplotlib-inline=0.1.6=py311hecd8cb5_0
  - mdurl=0.1.0=py311hecd8cb5_0
  - mkl=2023.1.0=h8e150cf_43559
  - mkl-service=2.4.0=py311h6c40b1e_1
  - mkl_fft=1.3.8=py311h6c40b1e_0
  - mkl_random=1.2.4=py311ha357a0b_0
  - mpi=1.0=mpich
  - mpich=4.1.1=hc226d05_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.5.6=py311hecd8cb5_0
  - numexpr=2.8.7=py311h728a8a3_0
  - numpy=1.26.0=py311h728a8a3_0
  - numpy-base=1.26.0=py311h53bf9ac_0
  - openssl=3.1.3=h8a1eda9_0
  - orc=1.7.4=h995b336_1
  - packaging=23.1=py311hecd8cb5_0
  - pandas=2.0.3=py311hdb55bb0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.3=py311hecd8cb5_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py311hcec6c5f_1
  - pip=23.2.1=py311hecd8cb5_0
  - platformdirs=3.10.0=py311hecd8cb5_0
  - prompt-toolkit=3.0.36=py311hecd8cb5_0
  - protobuf=3.20.3=py311hcec6c5f_0
  - psutil=5.9.0=py311h6c40b1e_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - py-xgboost=1.7.3=py311hecd8cb5_0
  - pyarrow=11.0.0=py311hf41f4e6_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pydeck=0.7.1=py311hecd8cb5_0
  - pygments=2.15.1=py311hecd8cb5_1
  - pympler=0.9=py_0
  - pyopenssl=23.2.0=py311hecd8cb5_0
  - pyparsing=3.0.9=py311hecd8cb5_0
  - pyrsistent=0.18.0=py311h6c40b1e_0
  - pysocks=1.7.1=py311hecd8cb5_0
  - python=3.11.5=hf27a42d_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py311hecd8cb5_0
  - pyzmq=25.1.0=py311hcec6c5f_0
  - re2=2022.04.01=he9d5cce_0
  - readline=8.2=hca72f7f_0
  - requests=2.31.0=py311hecd8cb5_0
  - rich=13.3.5=py311hecd8cb5_0
  - scikit-learn=1.2.2=py311hcec6c5f_0
  - scikit-learn-intelex=2023.1.1=py311hecd8cb5_0
  - scipy=1.11.3=py311h224febf_0
  - setuptools=68.0.0=py311hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=4.0.0=pyhd3eb1b0_0
  - snappy=1.1.9=he9d5cce_0
  - sqlite=3.41.2=h6c40b1e_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.0=py311hb3a5e46_0
  - streamlit=1.24.1=py311hecd8cb5_0
  - tbb=2021.8.0=ha357a0b_0
  - tenacity=8.2.2=py311hecd8cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h5d9f67b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.12.0=py311hecd8cb5_0
  - tornado=6.3.3=py311h6c40b1e_0
  - traitlets=5.7.1=py311hecd8cb5_0
  - typing_extensions=4.7.1=py311hecd8cb5_0
  - tzdata=2023c=h04d1e81_0
  - tzlocal=2.1=py311hecd8cb5_1
  - urllib3=1.26.16=py311hecd8cb5_0
  - utf8proc=2.6.1=h9ed2024_0
  - validators=0.18.2=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.41.2=py311hecd8cb5_0
  - widgetsnbextension=4.0.5=py311hecd8cb5_0
  - xgboost=1.7.3=py311hecd8cb5_0
  - xz=5.4.2=h6c40b1e_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.11.0=py311hecd8cb5_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.5=hc035e20_0
  - pip:
      - arrow==1.3.0
      - binaryornot==0.4.4
      - chardet==5.2.0
      - cookiecutter==2.4.0
      - python-slugify==8.0.1
      - pyyaml==6.0.1
      - text-unidecode==1.3
      - types-python-dateutil==2.8.19.14
prefix: /Users/micheal/anaconda3/envs/11_mini_project
